# Generated by Django 3.0.5 on 2020-04-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200423_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='Update Branch', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='Update DOB', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='passout',
            field=models.CharField(default='YEAR', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='workat',
            field=models.CharField(default='Update Working at', max_length=50),
            preserve_default=False,
        ),
    ]
