# Generated by Django 3.0.5 on 2020-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
